apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    impl: go
    name: route53
    role: support
    tier: backend
  name: route53
spec:
  replicas: 1
  selector:
    name: route53
  template:
    metadata:
      labels:
        impl: go
        name: route53
        role: support
        tier: backend
      name: route53
    spec:
      containers:
      - env:
        - name: NAMESPACE
          value: default
        - name: TLD
          value: my.company.com
        - name: AWS_ACCESS_KEY_ID
          value: XXXXXXXXXXXXXXXXXXXXXXX
        - name: AWS_SECRET_ACCESS_KEY
          value: XXXXXXXXXXXXXXXXXXXXXX
        - name: AWS_REGION
          value: eu-central-1
        image: 944590742144.dkr.ecr.eu-west-1.amazonaws.com/apply/smart-route53:latest
        name: route53
        resources:
          limits:
            cpu: 100m
            memory: 20Mit
      imagePullSecrets:
      - name: registry-key
      nodeSelector:
        beta.kubernetes.io/instance-type: t2.medium
